version: "3.8"
services:
  api:
    build: .
    ports:
      - "5000:80"
    environment:
      - DOTNET_ConnectionStrings__Postgres=Host=db;Database=mydb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
